[package]
name = "메이플_temp_del"
version = "0.0.5"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rayon = "1.7"
dirs = "4.0"
walkdir = "2.3.2"
num_cpus = "1.15"

[build-dependencies]
winres = "0.1"